### ISSUE TITLE
Support for Shelly Plus 2PM and Shelly Plus I4

### ISSUE THREAD

**Issue by marcel255** [alexryd/homebridge-shelly-ng#12] opened 2022-02-24 15:07 UTC
Hello, can you please add these two shelly for support :) 

Shelly Plus 2PM
`{"name":null,"id":"shellyplus2pm-a8032ab7260c","mac":"A8032AB7260C","model":"SNSW-002P16EU","gen":2,"fw_id":"20220214-154302/0.10.0-beta3-gd36941f","ver":"0.10.0-beta3","app":"Plus2PM","auth_en":false,"auth_domain":null,"profile":"switch"}`

Shelly Plus I4
`{"name":null, "id":"shellyplusi4-083af20140a4", "mac":"083AF20140A4", "model":"SNSN-0024X", "gen":2, "fw_id":"20220120-094630/i4prod1-g480b553", "ver":"i4prod1", "app":"PlusI4", "auth_en":false,"auth_domain":null}`

**Comment by SpaceRichard** [comment] 2022-02-25 18:06
As for the Plus i4 there ist already #6 

Here my code for Plus 2 PM
`{"name":null,"id":"shellyplus2pm-a8032ab64d70","mac":"A8032AB64D70","model":"SNSW-002P16EU","gen":2,"fw_id":"20220214-154302/0.10.0-beta3-gd36941f","ver":"0.10.0-beta3","app":"Plus2PM","auth_en":false,"auth_domain":null,"profile":"switch"}`

**Comment by alexryd** [comment] 2022-03-01 05:33
Yes I'm working on adding both devices.

**Comment by okonet** [comment] 2022-03-12 07:52
@alexryd I noticed that you already have code for 2PM. Any chance you could cut a release with support for this device or is there something missing from it? Appreciate you working on it!

**Comment by alexryd** [comment] 2022-03-12 12:23
I’ve just released a beta version with support for the 2 PM and the I4. Since I don’t have the devices myself I need someone else to test them.

Are you using your 2 PM as a switch or to control a window cover?

**Comment by SpaceRichard** [comment] 2022-03-12 14:24
@alexryd I have both. 
I4 in use and plus 2 PM on the testing table. 
What is the best way to try the beta?

**Comment by okonet** [comment] 2022-03-12 16:33
I'm using 2PM as switches but I might get some as covers too soon.

**Comment by okonet** [comment] 2022-03-12 16:35
I'm also wondering where did the release go. I don't see it on NPM nor here. Could you maybe release a 1.3 so we could install easily via the homebridge? I'll report issues and try helping fixing if necessary.

**Comment by marcel255** [comment] 2022-03-12 18:40
@okonet 
> I'm also wondering where did the release go. I don't see it on NPM nor here. Could you maybe release a 1.3 so we could install easily via the homebridge? I'll report issues and try helping fixing if necessary.

You can go to the Plugins section and click the Wrench icon on the plugin. Then click "install previous version". Select the beta version.

**Comment by marcel255** [comment] 2022-03-12 18:50
@alexryd 
Finding and adding the Shelly Plus 2 PM was successful. Also in Homebridge App, Works flawlessly.
I only use the Shelly Plus 2 PM as a switch. I don't have a window cover to test that.
I will also test Shelly Plus I4 asap.

Can you please add the function? That he does not add Switch 1 to the device category but takes the Name (device name) for Shelly Plus 1 PM and Shelly Plus 1. And for Shelly Plus 2 PM and Shelly Plus I4 the Channel Name.

Thank you for your good work!!

**Comment by SpaceRichard** [comment] 2022-03-12 18:50
@marcel255 thanks 👍🏼

**Comment by marcel255** [comment] 2022-03-12 19:06
@SpaceRichard you´re welcome :)

**Comment by SpaceRichard** [comment] 2022-03-12 20:44
@alexryd 
As @marcel255  said Plus 2 PM as switch works fine.

Plus 2 PM Cover Mode
I try the cover mode, without a real load just by the time limits. And I can't control it over the homebridge, it's also stuck in "opening"/"closing" within the Shelly app I can control the relais.

Shelly i4
I got 4 Button and 1 Service Label
But if I press a button I cant see any "update" within homebrige

And I support the request from @marcel255 with the channel name, with 2 i4 it's 10 items and it's a bit messy.
For the service Label you use already the device name.

Thanks so far!

**Comment by okonet** [comment] 2022-03-14 09:27
@marcel255 thanks for the hint. It worked!

I've tested a bit two 2PM devices since then I have some issues with them: even when triggered through the HomeKit, it wouldn't trigger the device change although I can switch on/off in the HomeKit. Today it's working just fine 🤷‍♂️ . I'm not sure if that's related to devices or the plugin since there are no debug logs visible (can I enable only for this plugin?) so I'd like to keep an eye on it for now.

**Comment by Kohlibrie** [comment] 2022-03-16 09:59
I use the Shelly Plus 2 PM in cover mode:
The roller shutter is displayed as a window in the home app:
![grafik](https://user-images.githubusercontent.com/14921560/158564266-ecc095ec-b825-40ac-9014-e495864a60e4.png)
Also when I switch the shutter appears a long time a loading icon at the roller shutter.

But for the first version, i can control the roller shutter by the home app.

**Comment by alexryd** [comment] 2022-03-25 06:57
@marcel255 I will have a look at the naming of the various switches and buttons but it's not a top priority right now.

@SpaceRichard To use the cover mode your device must be calibrated. HomeKit unfortunately doesn't support open/close with time limits.

@okonet I don't think homebridge supports enabling debug logs for individual plugins unfortunately.

@Kohlibrie Nice to hear that it's working 👍 Changing the type to a door or window cover instead will come in a later update. When you say a long time, how long do you mean? I'm not sure if there is anything I can do to reduce the lag.

**Comment by Sebbo02** [comment] 2022-04-04 18:24
Anyone else facing regular disconnection with the 2PMs? I have two of them in roller shutter mode. They work fine via the Shelly-Web-Interface, but in HomeKit they are loosing connection over night. A reboot fixes that again, but after a couple of hours they are gone again. Homebridge Log Shows : ,,Device Disconnected (Reason: )” & ,,Failed to set target position: Reqest Timeout” if I try to use them

**Comment by okonet** [comment] 2022-04-06 15:34
I also constantly have issues with connection but it also applies to the web UI when accessing via IP address. Most of the time both devices aren't available yet they seem to respond sometimes. I contacted Shelly support and they suggested to open them up and check the connection of the Wi-Fi antenna on the pcb board.

**Comment by eliziox** [comment] 2022-04-11 18:08
Hello, first, thanks for this plug-in!

I'm testing 2PM in cover mode too, and I have exactly the same problem that @Sebbo02 

Let us know if you need support or more tests to fix it :-)

**Comment by alexryd** [comment] 2022-04-15 14:01
I just released version 1.3.0 that should fix your disconnection issues by sending periodic pings and automatically reconnecting when a connection is closed.

**Comment by eliziox** [comment] 2022-04-15 14:48
Great to read this. Even if since 2 days I can't reproduce this issue.

Anyway, we have another issue with the % displayed on homekit when we use external button to control the cover (Homekit displays "Closing" indefinitely). However, it work perfectly when we control the cover under homekit directly.

**Comment by McGrummel** [comment] 2022-08-20 10:40
> I use the Shelly Plus 2 PM in cover mode: The roller shutter is displayed as a window in the home app: ![grafik](https://user-images.githubusercontent.com/14921560/158564266-ecc095ec-b825-40ac-9014-e495864a60e4.png) Also when I switch the shutter appears a long time a loading icon at the roller shutter.
> 
> But for the first version, i can control the roller shutter by the home app.

PM2 still recognized as a window instead of a roller shutter.

**Comment by alexryd** [comment] 2022-08-23 08:52
Version 1.6.0 that I just released adds support for changing the cover type from Window to Window Covering or Door.

**Closed** 2022-08-23 08:52 UTC
Labels: enhancement
